package actions

const PLAYER_HEALTH = 100
const MONSTER_HEALTH = 100

const PLAYER_MIN_ATTACK_VALUE = 5
const PLAYER_MAX_ATTACK_VALUE = 10
const PLAYER_MIN_SPECIAL_ATTACK_VALUE = 10
const PLAYER_MAX_SPECIAL_ATTACK_VALUE = 20
const PLAYER_MIN_HEAL_VALUE = 10
const PLAYER_MAX_HEAL_VALUE = 20

const MONSTER_MIN_ATTACK_VALUE = 9
const MONSTER_MAX_ATTACK_VALUE = 13
